alter PROCEDURE sp_createSlotsOfAllGameType
AS BEGIN
	SET NOCOUNT ON
	DECLARE @TOTAL_ROWS INT;
	DECLARE @OPENING_HOURS TIME
	DECLARE @CLOSING_HOURS TIME
	DECLARE @GAME_TYPE_ID BIGINT
	DECLARE @DURATION BIGINT

	SELECT * INTO #TEMP FROM GameType
	SELECT @TOTAL_ROWS = COUNT(*) FROM #TEMP

	WHILE(@TOTAL_ROWS <> 0)
	BEGIN
		SELECT 
			TOP 1
			@GAME_TYPE_ID = id,
			@OPENING_HOURS = openingHours,
			@CLOSING_HOURS = closingHours,
			@DURATION = slotDuration
		FROM #TEMP

		EXECUTE sp_createSlotsByGameConfig @OPENING_HOURS,@CLOSING_HOURS, @GAME_TYPE_ID, @DURATION 

		DELETE  FROM #TEMP WHERE id = @GAME_TYPE_ID
		SET @TOTAL_ROWS -= 1
	END

	DROP TABLE #TEMP
END
