ALTER PROCEDURE sp_createSlotsByGameConfig
@OPENING_HOURS TIME
,@CLOSING_HOURS TIME
,@GAME_TYPE_ID BIGINT
,@DURATION BIGINT
,@days int
AS BEGIN
	SET NOCOUNT ON
	DECLARE @SLOT_START_TIME TIME = @OPENING_HOURS
	DECLARE @SLOT_ENDS_TIME TIME
	DECLARE @FLAG BIT = 1
	DECLARE @slotDate date
	DECLARE @count int = 1
	WHILE @count <= @days
	BEGIN
		SET @slotDate = DATEADD(DAY,@count,GETDATE())
		SET @SLOT_START_TIME = @OPENING_HOURS
		SET @FLAG = 1
		WHILE(ABS(DATEDIFF(MINUTE,@SLOT_START_TIME, @CLOSING_HOURS)) >= @DURATION or @FLAG = 1)
		BEGIN
			SET @SLOT_ENDS_TIME = DATEADD(MINUTE,@DURATION,@SLOT_START_TIME)
			INSERT INTO GameSlot (startsFrom,isAvailable,slotDate,endsAt,gameType_id)  VALUES (@SLOT_START_TIME,1,FORMAT(@slotDate,'yyyy-MM-dd'),@SLOT_ENDS_TIME,@GAME_TYPE_ID)
			SET @SLOT_START_TIME =@SLOT_ENDS_TIME
			set @FLAG = 0
		END
		SET @count = @count + 1
	END
END